### ISSUE TITLE
Its shit

### ISSUE THREAD

**Issue by brys0** [GoogleBot-Development/Support#3]
# Why must you block me on new years asshole?

I was literally trying to be nice and i get blocked
> Stop sucking your own dick so much your distracted from even seeing in front of you

```kt
i've literally never met someone so braindead as you are towards others opinions.
```

1. If you want success your going to have to listen to others. Something you failed at doing for me.
2. You also need to work with others that you may not like, case in point asshole.
3. Listen to criticism don't be fake as your countless of reviews are. Seriously man your not tricking anyone, those reviews were written by your staff team, or friends. Grow the fuck up.

I hope life goes well for you and you learn your lesson sooner or later it'll bite you in the ass mate.

**Comment by brys0** [comment]
I hope you open enough to respond to this. And not freak your shit, to try and remove me. You can't you won't ever. Don't even try.

**Comment by brys0** [comment]
Think i was lying look 
[![img](https://images-ext-1.discordapp.net/external/zJmAHC2FbV5sNrNBlJ4H2-eK91-AopiZjNymbME-PK0/https/i.imgur.com/iYmHLEN.png)

**Comment by brys0** [comment]
"We expect respectful discussions and constructive feedback/criticism when discussing/commenting on reports. Please keep your discussions on topic and to the point to prevent unnecessary conversations that may lead to arguments. We encourage all members of both communities to speak up about your ideas and suggestions. This provides us with a better understanding of what is more important to you and the best possible solutions for issues." 

First of all if your going to make a rule such as that at least fucking follow it why don't you?

**Comment by TheNintendoNerd3151** [comment]
1.Imagine asking for help on how to make a discord bot and then blocking the dude when all he did was to try to help you = pisshead move
2.Using "Google" in the name is gonna get your Ass sued off by either Discord or google, 
3.Being an asshole to a nice guy is not funny at the more rather rude and annoying
4.Grow some braincells, it _**Might**_ Help you in the future
Have a nice night, you dense clown 
Ps. not directed at brys rather at the clown of a developer
Cheers

**Comment by brys0** [comment]
Oh and don't try and hire my friends man. Thanks😉

**Comment by Jeydin21** [comment]
They came to me fucker

**Comment by Jeydin21** [comment]
**LEAVE ME ALONE. YOU'VE BEEN HARASSING ME SINCE AUGUST. DROP THIS**

**Comment by Jeydin21** [comment]
And Brys, don't you think for a second that you're gonna suddenly be my mom or something lmAo

**Comment by Jeydin21** [comment]
Imagine making an alt to harass me lmao

**Comment by Jeydin21** [comment]
I blocked you because 99.999999999999999999999999999999999999% of what comes out of you is random bullshit man, you even knew this

**Comment by Jeydin21** [comment]
> "We expect respectful discussions and constructive feedback/criticism when discussing/commenting on reports. Please keep your discussions on topic and to the point to prevent unnecessary conversations that may lead to arguments. We encourage all members of both communities to speak up about your ideas and suggestions. This provides us with a better understanding of what is more important to you and the best possible solutions for issues."
> 
> First of all if you're going to make a rule such as that at least fucking follow it why don't you?

I don't know, I think you should be the one following it, not me

**Comment by Jeydin21** [comment]
> 1.Imagine asking for help on how to make a discord bot and then blocking the dude when all he did was to try to help you = pisshead move
> 2.Using "Google" in the name is gonna get your Ass sued off by either Discord or google,
> 3.Being an asshole to a nice guy is not funny at the more rather rude and annoying
> 4.Grow some braincells, it _**Might**_ Help you in the future
> Have a nice night, you dense clown
> Ps. not directed at brys rather at the clown of a developer
> Cheers

Ok alt man lmao

**Comment by Jeydin21** [comment]
lmao you say my bot's shit? Then why do so many people use it? Your bot isn't even verified (I think)

**Comment by Jeydin21** [comment]
> I hope you open enough to respond to this. And not freak your shit, to try and remove me. You can't you won't ever. Don't even try.

Idk, I'm doing pretty fine at the moment lmao. Fix that grammar though, I don't really understand what you're saying :<

**Comment by Jeydin21** [comment]
And who cares if most of them are my friends? You yourself are getting like 5 of your friends to team up and fight a "war" against me, this isn't war, this is just continued and prolonged harassment by a person who doesn't understand that the person they're trying to harm just wants to leave all of this behind and move on.
